[workspace]
resolver = "2"
members = [
    "packages/lfmt",
    "packages/n",
    "packages/viopen",
    "packages/vipath",
    "packages/which",
    "packages/win-envedit",
    "packages/wsclip"
]

[workspace.dependencies.cu]
package = "pistonite-cu"
version = "0.7.4"

