[package]
name = "which"
description = "Crossplatform which"
license = "MIT"
version = "0.1.3"
edition = "2024"
publish = false

[dependencies]
clap = { version = "4.5.57", features = ["derive"] }
which = "8.0.0"

[[bin]]
path = "main.rs"
name = "which"
