[package]
name = "viopen"
description = "Open editor and wait for finish"
license = "MIT"
version = "0.1.1"
edition = "2024"
publish = false

[dependencies]
cu = { workspace = true, features = [ "process" ] }
shell-words = "1.1.1"

[lib]
path = "lib.rs"

[[bin]]
name = "viopen"
path = "main.rs"

[features]
default = []
print = ["cu/print"]
coroutine = ["cu/coroutine"]
