[package]
name = "win-envedit"
description = "Simple wrapper for editing Windows environment variables"
license = "MIT"
version = "0.1.3"
edition = "2024"
publish = false

[target.'cfg(windows)'.dependencies]
cu.workspace = true
winreg = "0.55.0"

[lib]
path = "lib.rs"

